### PR TITLE
Pin paramiko as a requirement

### PR DESCRIPTION
**Pull request by dmannarino**
In order to make a release I had to manually upgrade my paramiko to 1.16.0.

@ksnavely @petevg @evansde77 @shudgston @appeltel @jcounts

### CODE REVIEW

**Comment by ksnavely** [comment]
+1

**Comment by ksnavely** [comment]
My bad, +1

**Comment by evansde77** [comment]
This isnt actually needed in the requirements file, as it is a dependency of fabric, so you have to do a pip install --upgrade fabric. I need to find a way to update the venv as part of a selfupdate...

**Comment by evansde77** [comment]
I would rather this didnt get merged as it would mean we would have to keep paramiko in sync with fabric when we should just be using fabric, but there is an upgrade story for the selfupdate command that i captured in issue https://github.com/evansde77/cirrus/issues/98

**Comment by ksnavely** [comment]
Ooh, that's where it's coming from.

**Comment by ksnavely** [comment]
Yeah we shouldn't pin paramiko if it's just coming from fabric.

**Pull request closed without merging**
